### ISSUE TITLE
Mise à jour des plugins

### ISSUE THREAD

**Issue by gtoubiana** [gtoubiana/acte#170]
## Minor Update

browser-sync devDep   2.13.0  ❯  2.14.0  => TODO => WATCH => /!\ BUGS => erreur reload
gulp-bump devDep      2.2.0   ❯  2.4.0   => TODO => RELEASE
gulp-git devDep       1.8.0   ❯  1.11.0  => TODO => RELEASE
## Major Update

eslint devDep                  2.10.2  ❯  3.3.1   => /!\ codeclimate = eslint 2
eslint-config-airbnb devDep    9.0.1   ❯  10.0.1  => /!\ eslint 3
eslint-plugin-jsx-a11y devDep  1.5.5   ❯  2.1.0   => /!\ eslint 3
eslint-plugin-react devDep     5.2.2   ❯  6.1.2   => /!\ eslint 3
github devDep                  1.4.0   ❯  2.5.1   => ?  => RELEASE

---

$ npm run test

**Comment by gtoubiana** [comment]
Minor Update New backwards-compatible features.
❯◯ browser-sync devDep  2.13.0  ❯  2.14.0  http://www.browsersync.io/
 ◯ gulp-bump devDep     2.2.0   ❯  2.4.0   http://github.com/stevelacy/gulp-bump
 ◯ gulp-git devDep      1.8.0   ❯  1.11.0  http://github.com/stevelacy/gulp-git
  
 Major Update Potentially breaking API changes. Use caution.
 ◯ eslint devDep                  2.10.2  ❯  3.3.1   http://eslint.org
 ◯ eslint-config-airbnb devDep    9.0.1   ❯  10.0.1  https://github.com/airbnb/javascript
 ◯ eslint-plugin-jsx-a11y devDep  1.5.5   ❯  2.1.0   https://github.com/evcohen/eslint-plugin-jsx-a11y#readme
 ◯ eslint-plugin-react devDep     5.2.2   ❯  6.1.2   https://github.com/yannickcr/eslint-plugin-react
 ◯ github devDep                  1.4.0   ❯  2.5.1   https://github.com/mikedeboer/node-github

**Comment by gtoubiana** [comment]
````
[16:14:45] Starting 'releases.github.releaser'...
null [ { state: 'fulfilled',
    value: 
     { url: 'https://api.github.com/repos/gtoubiana/acte/releases/3935054',
       assets_url: 'https://api.github.com/repos/gtoubiana/acte/releases/3935054/assets',
       upload_url: 'https://uploads.github.com/repos/gtoubiana/acte/releases/3935054/assets{?name,label}',
       html_url: 'https://github.com/gtoubiana/acte/releases/tag/0.0.16-4',
       id: 3935054,
       tag_name: '0.0.16-4',
       target_commitish: 'master',
       name: null,
       draft: false,
       author: [Object],
       prerelease: true,
       created_at: '2016-08-21T14:14:38Z',
       published_at: '2016-08-21T14:14:46Z',
       assets: [],
       tarball_url: 'https://api.github.com/repos/gtoubiana/acte/tarball/0.0.16-4',
       zipball_url: 'https://api.github.com/repos/gtoubiana/acte/zipball/0.0.16-4',
       body: '\n\n',
       meta: [Object] } } ]

/Users/toubia95/GitHub/acte/gulp/tasks/releases.js:181
      }
                   ^
TypeError: Cannot read property 'uploadAsset' of undefined
    at Immediate.conventionalGHReleaser (/Users/toubia95/GitHub/acte/gulp/tasks/releases.js:181:20)
    at Immediate.immediate._onImmediate (timers.js:590:18)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

```

**Comment by gtoubiana** [comment]
voir https://mikedeboer.github.io/node-github/

**Comment by gtoubiana** [comment]
Ok avec `github.repos.uploadAsset({ ... });`. voir https://mikedeboer.github.io/node-github/#api-repos-uploadAsset.

**Comment by gtoubiana** [comment]
Minor Update New backwards-compatible features.
❯◯ browser-sync devDep  2.13.0  ❯  2.14.0  http://www.browsersync.io/
  
 Major Update Potentially breaking API changes. Use caution.
 ◯ eslint devDep                  2.10.2  ❯  3.3.1   http://eslint.org
 ◯ eslint-config-airbnb devDep    9.0.1   ❯  10.0.1  https://github.com/airbnb/javascript
 ◯ eslint-plugin-jsx-a11y devDep  1.5.5   ❯  2.1.0   https://github.com/evcohen/eslint-plugin-jsx-a11y#readme
 ◯ eslint-plugin-react devDep     5.2.2   ❯  6.1.2   https://github.com/yannickcr/eslint-plugin-react
