### ISSUE TITLE
Saucelabs : 2 bugs IE9 + 1 bug IE8

### ISSUE THREAD

**Issue by gtoubiana** [gtoubiana/acte#261]
logs:

**Opera 12.16.0 (Linux 0.0.0): Executed 128 of 128 (2 FAILED) (0.606 secs / 0.092 secs)**

Opera 12.16.0 (Linux 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = la date grégorienne formatée par défaut. FAILED
	TypeError: 'Number.isInteger' is not a function
	dateVersJour([arguments not available])@/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:1610
	Jour([arguments not available])@/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:2629
	<anonymous function>([arguments not available])@/Users/toubia95/GitHub/acte/test/jasmine/lib/acteSpec.js:227
Opera 12.16.0 (Linux 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = Pas de correspondances. FAILED
	TypeError: 'Number.isInteger' is not a function
	dateVersJour([arguments not available])@/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:1610
	Jour([arguments not available])@/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:2629
	<anonymous function>([arguments not available])@/Users/toubia95/GitHub/acte/test/jasmine/lib/acteSpec.js:414

**IE 11.0.0 (Windows 8.1 0.0.0): Executed 128 of 128 (2 FAILED) (0.599 secs / 0.053 secs)**

IE 11.0.0 (Windows 8.1 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = la date grégorienne formatée par défaut. FAILED
	TypeError: Object doesn't support property or method 'isInteger'
	   at dateVersJour (/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:1610:9)
	   at Jour (/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:2629:9)
	   at Anonymous function (/Users/toubia95/GitHub/acte/test/jasmine/lib/acteSpec.js:227:5)
IE 11.0.0 (Windows 8.1 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = Pas de correspondances. FAILED
	TypeError: Object doesn't support property or method 'isInteger'
	   at dateVersJour (/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:1610:9)
	   at Jour (/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:2629:9)
	   at Anonymous function (/Users/toubia95/GitHub/acte/test/jasmine/lib/acteSpec.js:414:5)

**IE 10.0.0 (Windows 8 0.0.0): Executed 128 of 128 (2 FAILED) (0.67 secs / 0.048 secs)**

IE 10.0.0 (Windows 8 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = la date grégorienne formatée par défaut. FAILED
	TypeError: Object doesn't support property or method 'isInteger'
	   at dateVersJour (/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:1610:9)
	   at Jour (/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:2629:9)
	   at Anonymous function (/Users/toubia95/GitHub/acte/test/jasmine/lib/acteSpec.js:227:5)
IE 10.0.0 (Windows 8 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = Pas de correspondances. FAILED
	TypeError: Object doesn't support property or method 'isInteger'
	   at dateVersJour (/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:1610:9)
	   at Jour (/Users/toubia95/GitHub/acte/test/jasmine/lib/acte.js:2629:9)
	   at Anonymous function (/Users/toubia95/GitHub/acte/test/jasmine/lib/acteSpec.js:414:5)

**IE 9.0.0 (Windows 7 0.0.0): Executed 128 of 128 (2 FAILED) (0.569 secs / 0.063 secs)**

IE 9.0.0 (Windows 7 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = la date grégorienne formatée par défaut. FAILED
	TypeError: Object doesn't support property or method 'isInteger'
IE 9.0.0 (Windows 7 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = Pas de correspondances. FAILED
	TypeError: Object doesn't support property or method 'isInteger'

**IE 8.0.0 (Windows 7 0.0.0): Executed 128 of 128 (3 FAILED) (0.548 secs / 0.531 secs)**

IE 8.0.0 (Windows 7 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = la date grégorienne formatée par défaut. FAILED
	TypeError: Object doesn't support this property or method
IE 8.0.0 (Windows 7 0.0.0) new acte.Jour().gregorien() new acte.Jour().gregorien() = Pas de correspondances. FAILED
	TypeError: Object doesn't support this property or method
IE 8.0.0 (Windows 7 0.0.0) Recettes Recette 4 : Date complète hebdomadaire ISO FAILED
	TypeError: Object doesn't support this property or method

**Comment by gtoubiana** [comment]
premier bug corrigé avec isFinite() en remplacement de Number.isInteger()

**Comment by gtoubiana** [comment]
il reste IE8:
```
IE 8.0.0 (Windows 7 0.0.0) Recettes Recette 4 : Date complète hebdomadaire ISO FAILED
TypeError: Object doesn't support this property or method
```

**Comment by gtoubiana** [comment]
modifié en:
```js
      expect(
        new acte.Jour('1/1/2006')
        .gregorien('', 0, (res, obj) => {
          const jour = obj.JS === 0 ? 7 : obj.JS;
          const semaine = obj.S === 0 ? 52 : acte.prefixeZero(obj.S);
          const an = obj.S === 0 ? obj.A - 1 : obj.A;

          return `${an}-W${semaine}-${jour}`;
        })
      ).toEqual('2005-W52-7');
```

**Comment by gtoubiana** [comment]
info : https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by gtoubiana** [comment]
- Utiliser le js reporter https://wiki.saucelabs.com/display/DOCS/Reporting+JavaScript+Unit+Test+Results+to+Sauce+Labs+Using+Jasmine
- Utiliser grunt pour saucelabs ? https://github.com/saucelabs/sauce-support/tree/master/JS/Jasmine/Jasmine%202

**Comment by gtoubiana** [comment]
Pour `gulp tests.saucelabs.ie8`, essayer d'ajouter es5-shim et es5-sham (https://github.com/es-shims/es5-shim) au specRunner.html

**Comment by gtoubiana** [comment]
les shims sont dans bower.
inclure les shim dans une balise spécifique IE8 !
réutiliser le js-reporter...

**Comment by gtoubiana** [comment]
voir


https://msdn.microsoft.com/library/jj676915(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/hh826025(v=vs.85).aspx

**Comment by gtoubiana** [comment]
Bug ie8 saucelabs avec karma 1.4
Repasser en 1.3 pour corriger
